"""Add issue audit log table

Revision ID: c5236dfe2004
Revises: 039dcce28f8d
Create Date: 2026-07-15 14:57:30.490263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5236dfe2004'
down_revision: Union[str, Sequence[str], None] = '039dcce28f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_audit_logs')
    # ### end Alembic commands ###
