"""Add B3-5 and B3-6 columns to reports

Revision ID: cf0dd450ddd8
Revises: d4f9e2b71a08
Create Date: 2026-07-16 23:15:43.700536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf0dd450ddd8"
down_revision: Union[str, Sequence[str], None] = "d4f9e2b71a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports", sa.Column("gps_source", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "reports", sa.Column("road_name", sa.String(length=200), nullable=True)
    )
    op.add_column("reports", sa.Column("weather", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "weather")
    op.drop_column("reports", "road_name")
    op.drop_column("reports", "gps_source")
    # ### end Alembic commands ###
