"""Add B-tree indexes for B3-7

Revision ID: d7a1f0962038
Revises: cf0dd450ddd8
Create Date: 2026-07-16 23:25:40.135657

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d7a1f0962038"
down_revision: Union[str, Sequence[str], None] = "cf0dd450ddd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_issues_created_at"), "issues", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_issues_status"), "issues", ["status"], unique=False)
    op.create_index(
        op.f("ix_reports_timestamp"), "reports", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_timestamp"), table_name="reports")
    op.drop_index(op.f("ix_issues_status"), table_name="issues")
    op.drop_index(op.f("ix_issues_created_at"), table_name="issues")
    # ### end Alembic commands ###
